# Generated by Django 4.2.3 on 2023-08-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsapp', '0002_remove_transaction_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='data',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_paid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='taxpayer_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='tin',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
