# Generated by Django 4.2.3 on 2023-08-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsapp', '0006_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
